decred/dcrdocs

README.md, mkdocs.yml
This requires an extra install with pip:
pip install fontawesome-markdown
Partially takes care of #49
=> Use Local font-awesome.

docs/mining/proof-of-work.md, docs/mining/proof-of-work/pool-mining/gominer/windows.md, mkdocs.yml
proof-of-work.md changes:
* Capitalize headings/sections
* Add decredpool.org to list of mining pools
* Add clause about spreading hashrate to smaller pools
* Add gominer to list of official software
* Format cgminer and ccminer sections to match gominer section
* Remove examples from Running the Software section
=> Edit proof-of-work.md, add gominer Windows guide

docs/getting-started/install-guide.md
Update install-guide.md .msi file to v0.8.1
=> Update install-guide.md .msi file to v0.8.1

docs/mining/proof-of-stake.md, mkdocs.yml
* Change Jumbucks pool to Ubiq pool
* Fix capitalization in proof-of-stake.md
* Fix capitalization in navigation menu
Fixes #71
=> Edit proof-of-stake.md and navigation menu

tpldcrdocs/css/base.css
=> Fix link colors

docs/advanced/contributing.md, mkdocs.yml
=> Add contributor help/instructions.

docs/advanced/storing-login-details.md, docs/mining/proof-of-stake.md
Working on #37
Added new ticket buyer commands.
Fixed grammar error in 'storing login details'.
Putting this up for comment, still needs some descriptions clarified.
=> Adjusting PoS guide to account for new ticket buyer.

docs/support-directory.md, docs/support.md, mkdocs.yml
Quickly created during my daughter's naptime. Please excuse any mistakes.
=> Add Support Page

docs/getting-started/constitution.md, mkdocs.yml
=> Add Decred Constitution

de_docs/getting-started/install-guide.md
=> Filename correction in install-guide.md

de_docs/about/license.md, de_docs/faq/errors.md, docs/about/license.md, ru_docs/about/license.md, ru_docs/faq/errors.md
Add (untranslated) new pages to language specific directories.
Closes #126
=> Update Copyright date.

de_docs/getting-started/beginner-guide.md, docs/getting-started/beginner-guide.md
=> Clarify that Solaris means Solaris/illumos

docs/faq/wallets-and-seeds.md, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/paymetheus.md, docs/getting-started/user-guides/web.md
=> Seed reuse warning

docs/faq/general.md
=> Add premine distribution info

docs/mining/proof-of-work/pool-mining/gominer/windows.md
=> Update gominer version in Windows Guide

docs/getting-started/beginner-guide.md
This was supposed to be an update to #120 to fix the above link, but due to a conflict I tried to delete the branch and start a new one with the same name. Github didn't like that and closed the PR and I can't reopen it, hence this new PR.
=> Updated Decrediton link.

de_docs/mining/proof-of-work.md, docs/mining/proof-of-work.md
=> Update latest gominer version in guide

de_docs/advanced/user-projects.md, de_mkdocs.yml, docs/advanced/user-projects.md, mkdocs.yml
=> Add 'User Projects' page

de_docs/getting-started/user-guides/decrediton-setup.md, de_mkdocs.yml
=> Update de_docs with new untranslated page

de_mkdocs.yml, mkdocs.yml
Change from 'dcrdocs' to 'Decred Documentation'.
Closes #156
=> Use more descriptive title for site

docs/mining/proof-of-stake.md
=> Change 'main pool' to more accurate 'ticket pool'

docs/getting-started/beginner-guide.md, docs/getting-started/install-guide.md, docs/getting-started/startup-basics.md, docs/getting-started/user-guides/dcrctl-basics.md, docs/getting-started/user-guides/dcrd-setup.md, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/decrediton-setup.md
=> Refactor beginner-guide.md and CLI Path to focus on dcrinstall

de_mkdocs.yml
=> Specify directory with language docs in yml

build_docs.sh
=> Create xx_docs directory before trying to copy into it.

README.md
=> Add translation guide to README.md

docs/faq/errors.md
Resolves #180 
Added instructions for revoking missed/expired tickets.
=> Update errors FAQ

tpldcrdocs/css/base.css
=> Ensure table text and list text are the same size as other text

README.md
=> Specify commit message format for translated files

docs/advanced/contributing.md, docs/advanced/dcrctl-usage.md, docs/advanced/program-options.md, docs/faq/errors.md, docs/faq/proof-of-stake/buying-tickets-and-fees.md, docs/faq/wallets-and-seeds.md, docs/getting-started/install-guide.md, docs/getting-started/startup-basics.md, docs/getting-started/user-guides/dcrctl-basics.md, docs/mining/proof-of-work/pool-mining/cgminer/linux.md, docs/mining/proof-of-work/pool-mining/cgminer/windows.md, docs/mining/proof-of-work/solo-mining/cgminer/linux.md, docs/mining/proof-of-work/solo-mining/cgminer/windows.md
=> Standardise CLI param placeholders.

build_docs.sh
=> Make build warnings fatal

docs/faq/general.md
=> Add project commitment not to trade premine.

de_docs/faq/proof-of-stake/general.md, de_mkdocs.yml, docs/faq/proof-of-stake/general.md, es_docs/faq/proof-of-stake/general.md, es_mkdocs.yml, mkdocs.yml
Resolves #197 
Added general FAQ by @animedow with edits by @fai04d.
=> Added General PoS FAQ

de_docs/getting-started/beginner-guide.md, docs/getting-started/beginner-guide.md, es_docs/getting-started/beginner-guide.md
Rewrote the introduction to remove the technical jargon.
=> Change intro for getting-started/beginner-guide.md

de_docs/getting-started/install-guide.md, docs/getting-started/install-guide.md, es_docs/getting-started/install-guide.md
=> Fix copy past error with darwin in example name for linux

docs/advanced/user-projects.md
=> Add dcrstatus to User Projects

de_docs/getting-started/beginner-guide.md, de_docs/getting-started/install-guide.md, de_docs/getting-started/user-guides/testnet-voting.md, docs/getting-started/beginner-guide.md, docs/getting-started/install-guide.md, docs/getting-started/user-guides/testnet-voting.md, es_docs/getting-started/beginner-guide.md, es_docs/getting-started/install-guide.md, es_docs/getting-started/user-guides/testnet-voting.md
=> Update relevant version numbers to 1.0.1

docs/advanced/block-header-specifications.md
=> Add StakeVersion to block headers.

es_mkdocs.yml
=> Add missing pages to es_mkdocs.yml

de_docs/advanced/simnet.md, de_mkdocs.yml, docs/advanced/simnet.md, es_docs/advanced/simnet.md, es_mkdocs.yml, mkdocs.yml
Closes #188.
Info taken from https://gist.github.com/davecgh/2992ed85d41307e794f6#file-using_btcd_simnet-md
=> Add simnet guide to advanced section.

docs/getting-started/install-guide.md
=> Add tag numbers to github download links.

docs/faq/general.md
=> Reference constitution on dcrdocs and not via forum.

docs/getting-started/beginner-guide.md, docs/getting-started/obtaining-dcr.md
Resolves #294 
Fixed broken links in obtaining-dcr.md. Also found a broken link in beginner-guide.md; fixed that too.
=> Fixed broken links.

docs/advanced/inflation.md
=> Add block time to inflation page.

build_docs.sh
=> Set build_docs.sh exit status.

.travis.yml, README.md, requirements.txt
=> Use travis to test and add requirements.txt for install.

docs/mining/proof-of-stake.md
=> Add ultrapool.eu and remove dcrstakes.com.

de_docs/advanced/manual-cli-install.md, de_docs/getting-started/beginner-guide.md, de_docs/getting-started/startup-basics.md, de_docs/getting-started/user-guides/cli-installation.md, de_docs/getting-started/user-guides/dcrctl-basics.md, de_docs/getting-started/user-guides/dcrd-setup.md, de_docs/getting-started/user-guides/dcrwallet-setup.md, de_docs/getting-started/user-guides/dcrwallet-tickets.md, de_mkdocs.yml, docs/advanced/manual-cli-install.md, docs/getting-started/beginner-guide.md, docs/getting-started/startup-basics.md, docs/getting-started/user-guides/cli-installation.md, docs/getting-started/user-guides/dcrctl-basics.md, docs/getting-started/user-guides/dcrd-setup.md, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/dcrwallet-tickets.md, es_docs/advanced/manual-cli-install.md, es_docs/getting-started/beginner-guide.md, es_docs/getting-started/startup-basics.md, es_docs/getting-started/user-guides/cli-installation.md, es_docs/getting-started/user-guides/dcrctl-basics.md, es_docs/getting-started/user-guides/dcrd-setup.md, es_docs/getting-started/user-guides/dcrwallet-setup.md, es_docs/getting-started/user-guides/dcrwallet-tickets.md, es_mkdocs.yml, mkdocs.yml, tpldcrdocs/toc.html
=> Move manual CLI setup to advanced section

docs/getting-started/obtaining-dcr.md
Resolves #307 
Added https://changelly.com/
=> Updated "Obtaining DCR" to include https://changelly.com/

docs/mining/proof-of-work.md
=> Move cgminer and ccminer into Unofficial Miners.

de_docs/advanced/manual-cli-install.md, de_docs/getting-started/beginner-guide.md, de_docs/getting-started/user-guides/cli-installation.md, de_docs/getting-started/user-guides/testnet-voting.md, docs/advanced/manual-cli-install.md, docs/getting-started/beginner-guide.md, docs/getting-started/user-guides/cli-installation.md, docs/getting-started/user-guides/decrediton-setup.md, docs/getting-started/user-guides/paymetheus.md, docs/getting-started/user-guides/testnet-voting.md, es_docs/advanced/manual-cli-install.md, es_docs/getting-started/beginner-guide.md, es_docs/getting-started/user-guides/cli-installation.md, es_docs/getting-started/user-guides/testnet-voting.md
=> Update docs for v1.0.3

de_docs/getting-started/beginner-guide.md, docs/getting-started/beginner-guide.md, docs/getting-started/user-guides/paymetheus.md, es_docs/getting-started/beginner-guide.md
=> Update PM version to 1.0.4

docs/getting-started/user-guides/decrediton-setup.md
=> Fixed a broken link

docs/advanced/verifying-binaries.md
On step two, there is an instruction to download some files here, but there is not link.
Step three title is duplicated
=> Setting link and fixing step order

de_docs/getting-started/user-guides/using-paymetheus.md, docs/getting-started/user-guides/using-paymetheus.md, es_docs/getting-started/user-guides/using-paymetheus.md
=> Remove old advice about stakepools.

de_docs/mining/proof-of-work/pool-mining/gominer/linux.md, de_mkdocs.yml, docs/mining/proof-of-work/pool-mining/gominer/linux.md, es_docs/mining/proof-of-work/pool-mining/gominer/linux.md, es_mkdocs.yml, mkdocs.yml
Closes #201 
The supersedes #215 which was abandoned.  It is basically just a fixup of that PR which I will close.
=> gominer linux instructions

docs/getting-started/obtaining-dcr.md
=> Remove rfp and add contractors.

docs/getting-started/user-guides/web.md
=> Remove untrue statement about testnet.

docs/getting-started/user-guides/dcrwallet-tickets.md, tpldcrdocs/toc.html
=> Remove deprecated ticketbuyer options

docs/advanced/contributing.md
=> Added Missing Parenthesis

docs/faq/general.md
=> lead > led.

docs/getting-started/beginner-guide.md, docs/getting-started/user-guides/decrediton-setup.md
=> decrediton for windows.

docs/getting-started/using-testnet.md
=> update instructions for decrediton on testnet.

.dockerignore, .gitignore, Dockerfile, Dockerfile-build, Dockerfile-serve, README.md, build_docker.sh, build_docs.sh
=> build dcrdocs in docker.

docs/faq/proof-of-stake/voting-tickets.md
change "less" to "fewer" because we are talking about discrete amounts
=> grammatical correction

docs/faq/errors.md
Resolves #316 
Remove PM CLI guide.
Updated missed/expired tickets locked to reflect changes in Decrediton 1.1.1
=> Removed Paymetheus rescan steps and added note to advise of Decredition.

docs/advanced/contributing.md, src/i18n/ar/advanced/contributing.md, src/i18n/de/advanced/contributing.md, src/i18n/el/advanced/contributing.md, src/i18n/es/advanced/contributing.md, src/i18n/fi/advanced/contributing.md, src/i18n/fr/advanced/contributing.md, src/i18n/hr/advanced/contributing.md, src/i18n/id/advanced/contributing.md, src/i18n/it/advanced/contributing.md, src/i18n/ja/advanced/contributing.md, src/i18n/ko/advanced/contributing.md, src/i18n/pl/advanced/contributing.md, src/i18n/pt/advanced/contributing.md, src/i18n/ru/advanced/contributing.md, src/i18n/sr/advanced/contributing.md, src/i18n/uk/advanced/contributing.md, src/i18n/zh/advanced/contributing.md
=> Update setup to use dep instead of Glide

docs/getting-started/obtaining-dcr.md
Included litebit.eu, cryptopia and exodus
=> Updated list of exchanges

docs/getting-started/obtaining-dcr.md
=> Update exchange list.

docs/index.md
=> Changed public key to private key in bank analogy

docs/getting-started/cli-differences.md, docs/getting-started/startup-basics.md, docs/getting-started/user-guides/decrediton-setup.md
=> Add decrediton data directory. Mention log files.

docs/css/style.css, mkdocs.yml
=> Disable navigation tabs - use side menu.

docs/getting-started/cli-differences.md, docs/getting-started/user-guides/decrediton-setup.md
=> Use uppercase in macOS paths

docs/getting-started/obtaining-dcr.md
=> Remove icons from Obtaining Decred page

docs/getting-started/obtaining-dcr.md, docs/mining/proof-of-work/pool-mining/cgminer/linux.md, docs/mining/proof-of-work/pool-mining/cgminer/windows.md, docs/mining/proof-of-work/pool-mining/gominer/linux.md, docs/mining/proof-of-work/pool-mining/gominer/windows.md, docs/mining/proof-of-work/solo-mining/cgminer/linux.md, docs/mining/proof-of-work/solo-mining/cgminer/windows.md
=> Fix header levels.

mkdocs.yml
=> Add youtube link and dcrdocs repo name.

mkdocs.yml
Closes #437 and I actually made a couple of extra changes to the nav menu:
- Added a `Wallets` section for Decrediton, CLI and Web wallet docs.
- Moved PoS FAQs into the PoS section. Same for PoW.
=> Reorg nav menu. Add Wallet section.

docs/getting-started/obtaining-dcr.md
=> Add flyp.me exchange.

docs/css/style.css
=> Increase size of social media icons.

docs/getting-started/obtaining-dcr.md
Adding Godex.io, fex.hq and upbit.com as exchanges to obtain dcr
closes #460
=> Adding godex.io exchange

docs/faq/wallets-and-seeds.md, src/i18n/de/faq/wallets-and-seeds.md, src/i18n/el/faq/wallets-and-seeds.md, src/i18n/ja/faq/wallets-and-seeds.md, src/i18n/pl/faq/wallets-and-seeds.md, src/i18n/zh/faq/wallets-and-seeds.md, theme_override/base.html, theme_override/partials/social.html
=> Update word count to 33, resolves #464

docs/getting-started/obtaining-dcr.md
fixes #463 
makes #481 PR obsolete
=> new fiat exchanges and payment processors

docs/getting-started/obtaining-dcr.md
In addition to us, Cumberland also trades DCR. I will add others as I find them.
=> Adding OTC desks to the liquidity providers

README.md
=> Remove outdated README section for serving translated versions

docs/getting-started/user-guides/decrediton-setup.md
=> Update decrediton download instructions for 1.2.1.

docs/advanced/program-options.md
=> Remove unimplemented dcrwallet command.

docs/faq/configuration.md
=> List port numbers for dcrwallet and dcrd.

docs/faq/wallets-and-seeds.md, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/web.md
=> Remove FAQ about multiple wallets/same seed.

requirements.txt
=> Update python libs.

docs/getting-started/obtaining-dcr.md
Litebit de-listed DCR over a month ago and said they don't plan to re-list any time soon.
=> Removed litebit.eu

docs/css/style.css, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/decrediton-setup.md, docs/mining/proof-of-work/pool-mining/gominer.md, mkdocs.yml
=> Introduce usage of admonitions for warnings.

requirements.txt
=> Rollback mkdocs upgrade to 2.7.3

docs/getting-started/beginner-guide.md
=> Use markdown lists rather than html formatting.

docs/getting-started/obtaining-dcr.md
=> Link to exchange page on main decred website.

docs/getting-started/using-the-block-explorer.md
Commits need to be squashed into one
=>  Add dcrdata to explorer section

docs/css/style.css
before:
https://i.imgur.com/iSUKjqb.png
after:
https://i.imgur.com/ft7BYgs.png
=> Disable min-width for headers in tables with at least 7 columns

docs/css/style.css
Polishing the changes added in #577. 
Closes #568
Closes #566
Closes #565
=> Update appearance of tables, quotes and admonitions.

docs/css/fonts.css
Polishing the changes added in #577.
Closes #560.
=> Update link appearance.

docs/faq/general.md
Also:
- Fix the order of the footnotes on the page
- Remove a footnote to the constitution. (its just an internal link to another docs page)
Closes #552
=> Add link to the pre-mine transaction.

docs/mining/proof-of-work.md, docs/mining/proof-of-work/pool-mining/gominer.md
=> Remove inactive PoW pools.

docs/css/style.css
Polishing the changes added in #577.
Closes #564 
Closes #563
=> Update code appearance.

docs/advanced/contributing.md
This text update is in accordance with: https://github.com/decred/dcrdocs/issues/611#issuecomment-420929389
=> contributing.md: Update intro paragraph in Go section

docs/getting-started/constitution.md
Some aspects of the constitution are obsolete, some are yet to be put into practice, Politeia proposals will soon bring it up to date. Closes #576
=> Note about forthcoming constitutional reform (#576)

docs/index.md
Updates intro paragraph on homepage ( Closes #610 ). This was reused from a rewrite of the original paragraph done for the dcrd README (https://github.com/decred/dcrd) -- rewrite from @davecgh.
=> Updates intro paragraph on home page

docs/index.md
- Use markdown comment-style
- remove stray </i>
- autocomplete is not valid for checkbox
=> Various cleanups

docs/faq/configuration.md
=> Update link to dcrd sample config

docs/mining/proof-of-stake.md
=> Fix broken link to stakepool list.

docs/css/fonts.css, docs/css/style.css
=> Use new dark blue.

docs/getting-started/user-guides/agenda-voting.md
=> Fix inconsistent page title.

docs/getting-started/user-guides/how-to-vote.md
=> Fix broken link in how-to-vote.md.

docs/advanced/manual-cli-install.md, docs/getting-started/user-guides/cli-installation.md, docs/getting-started/user-guides/decrediton-setup.md
=> OS specific instructions in collapsible panels.

docs/governance/politeia.md
=> Fix a broken link in politeia.md.

docs/getting-started/user-guides/dcrwallet-tickets.md
=> Remove deprecated ticketbuyer options.

mkdocs.yml
Closes #629.
I know #630 also includes this, but that has been inactive for a month.
=> Add footer links for facebook and linkedin.

README.md, docs/getting-started/beginner-guide.md, docs/getting-started/startup-basics.md, docs/getting-started/user-guides/dcrctl-basics.md, docs/getting-started/user-guides/dcrd-setup.md, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/dcrwallet-tickets.md, docs/governance/consensus-rules-voting.md, docs/governance/how-to-vote.md, docs/wallets/cli/cli-installation.md, docs/wallets/cli/os-differences.md, docs/wallets/web.md, httpd.conf, mkdocs.yml
More work for #659.
Moves a few more pages into their proper directories.
=> Redirection for voting page and some wallet pages

docs/advanced/navigating-politeia-data.md, docs/contributing/contributor-compensation.md, docs/getting-started/user-guides/dcrwallet-tickets.md, docs/getting-started/user-guides/decrediton-setup.md, docs/getting-started/user-guides/using-decrediton.md, docs/mining/proof-of-work.md, docs/mining/proof-of-work/pool-mining/gominer.md, docs/wallets/cli/cli-installation.md, src/i18n/de/getting-started/user-guides/web.md
=> Clean some duplicated urls, update contractor count, remove posmaster.info

docs/glossary.md
=> Fixes typo glossary

docs/faq/proof-of-stake/stake-pools.md, mkdocs.yml
Implements jargon change (stakepools -> Voting Service Provider (VSP) on stakepools page ( Closes #713 ).
=> Jargon update on stakepools page

docs/glossary.md
Updates the definition for Address in the glossary, with input from @davecgh ( Closes #710 ).
=> Updates glossary definition address

docs/getting-started/beginner-guide.md, mkdocs.yml
=> Add weibo links.

docs/governance/consensus-rules-voting.md, docs/governance/introduction-to-decred-governance.md
=> Change agenda voting to consensus rule voting.

docs/glossary.md
Took a stab at a glossary definition for Simple Payment Verification (SPV) ( Closes #703 ).
=> Adds SPV glossary

docs/faq/configuration.md, docs/getting-started/user-guides/decrediton-setup.md, docs/wallets/spv.md, mkdocs.yml
=> Add guide for SPV.

httpd.conf
=> Use mkdocs generated 404 page.

docs/faq/errors.md, docs/faq/wallets-and-seeds.md, docs/getting-started/user-guides/dcrctl-basics.md, docs/getting-started/user-guides/dcrwallet-tickets.md
=> Encourage the use of promptsecret.

docs/glossary.md
Took a crack at adding a definition for the signature (below) ( Closes #704 ).
A cryptographic mechanism that proves that the owner of the private key has approved a transaction.
=> Adds definition signature to glossary

docs/mining/proof-of-work.md
Mentions the BLAKE-256 hashing algorithm (important detail) on the PoW page ( Closes #744 ).
=> BLAKE-256 mention PoW page

docs/faq/proof-of-stake/general.md, docs/mining/proof-of-stake.md
Opening a new PR after syncing my fork.
Closes #749
=> Left over Jargon

docs/faq/wallets-and-seeds.md, docs/index.md
Added a table that displays the various types of addresses and associated information. Also copied the subsidy breakdown table to the home page, it seems to make the most sense being there.
Closes #762 
Closes #748
=> Tables - Addresses and other minor improvements

mkdocs.yml
It feels weird having the "intro" as the second menu item. This PR makes it the first.
=> Move Intro to top of governance submenu.

httpd.conf
=> Fix 2 broken redirects.

docs/css/fonts.css, docs/governance/politeia/example-proposals.md
No copy changes - only formatting.
Closes #759
=> Use bq to improve formatting of example proposals.

docs/wallets/cli/dcrwallet-setup.md
=> Remove broken links.

docs/faq/proof-of-stake/general.md, docs/proof-of-stake/proof-of-stake.md
=> Correct average ticket vote times.

docs/faq/blocks.md
Closes #549
Reword and remove broken links.
=> Re-word passage about orphan blocks.

docs/advanced/inflation.md
Stealing DaveC's words from chat :)
Closes #628
=> Remove PoW reward from block 1.

docs/faq/proof-of-stake/general.md
=> New FAQ for ticket pool target size.

docs/glossary.md
=> Add PoW & Work to glossary.

docs/advanced/inflation.md
Adds reasoning on the inflation page for the 60/30/10 block reward split ( Closes #707 ).
=> Adds reasoning for 60/30/10 split to inflation page

docs/advanced/solo-proof-of-stake-voting.md, docs/faq/wallets-and-seeds.md, docs/wallets/cli/dcrwallet-setup.md, docs/wallets/decrediton/decrediton-setup.md, mkdocs.yml
=> Remove seed warning duplication.

docs/css/fonts.css, docs/css/style.css, requirements.txt
Also makes required .css changes
https://squidfunk.github.io/mkdocs-material/release-notes/#material-3x-to-4x
=> Update to mkdocs-material 4.0.1

docs/mining/proof-of-work.md, docs/mining/proof-of-work/pool-mining/gominer.md, mkdocs.yml
Adds a variable for gominer versioning ( Closes #866 ).
=> Adds variable for gominer

requirements.txt
Updated Mkdocs theme to 4.0.2. Tested locally and everything looks good ( Closes #870 ).
=> Updates mkdocs-material to 4.0.2

docs/wallets/cli/dcrctl-rpc-commands.md
=> update link to dcrd rpc docs.

mkdocs.yml
=> Move elements in mkdocs.yml to restore fa icons.

docs/governance/politeia/proposal-guidelines.md
Adds list of requirements to proposal guidelines for proposals seeking funds from the treasury ( Closes #881 ).
=> Updates Politeia guidelines with new requirements

docs/proof-of-stake/overview.md
=> ticket expiry period in blocks.

conf/nginx.conf
=> Fix redirects again.

docs/getting-started/beginner-guide.md
Standardized capitalization for bulleted lists in the [beginner guide](https://docs.decred.org/getting-started/beginner-guide/) (also skimmed the rest of the docs for same inconsistency, didn't find any)
Also standardized on using `-` instead of `(` (which seemed like the more awkward option) ( Closes #929 ).
=> Standardizes capitalization beginner guide

docs/governance/consensus-rule-voting/consensus-vote-archive.md
Updating page with the fixlnseqlocks vote and changed the flow of the page from the newest vote to oldest. Added links to dcrdata and abstain %.
(Closes #938)
=> update to the consensus archive page

docs/advanced/transaction-details.md
compatability -> compatibility
=> Fixes typo Transaction Details details page

README.md, docs/wallets/decrediton/decrediton-troubleshooting.md
Some of the issues listed on this page are likely to be resolved to be resolved in future releases, thus we should review this page when new releases are produced.
=> 'Last Updated' for decrediton troubleshooting page

docs/wallets/hardware-wallets.md
This PR adds support details to the hardware wallets page ( Closes #962 ).
=> Updates hardware wallet support details

docs/wallets/hardware-wallets.md
Changes date on hardware wallets page from US format to ISO global standard format.
=> Changes date to ISO format

docs/faq/wallets-and-seeds.md
=> FAQ on 2FA.

docs/glossary.md
- Change
- Change Address
- Elliptic Curve
- Elliptic Curve Cryptography
- Smart Contract
=> New Glossary terms

docs/glossary.md
Adds UTXO definition to glossary ( Closes #1002 ).
=> Adds definition UTXO to glossary

docs/faq/proof-of-stake/general.md
Adds a question to the PoS FAQ (which we've gotten a few times now), "how can I get my DCR locked in tickets back?" ( Closes #1004 ). 
@noahpierau, I changed the question to "Can I cancel my ticket?" to make this more general. Does that still work, or do we want to be more specific?
=> Add faq answer can I cancel a ticket

docs/privacy/general-privacy.md, mkdocs.yml
Closes Dedicated Privacy page #816
=> Add Privacy to docs

docs/governance/overview.md
=> Improve Governance Overview page

docs/research/signature-script-isolation-and-fraud-proofs.md
=> Updates part about Segregated Witness

docs/glossary.md
=> Add regnet to glossary

docs/privacy/general-privacy.md
Implementing both of the suggestions from @s-ben in #1027 
The rest of the changes are just whitespace/line length
=> Finishing touches on Privacy guide

docs/wallets/decrediton/decrediton-setup.md
=> Update decrediton setup

docs/proof-of-stake/how-to-stake.md
Previous version makes it sound as if you absolutely need to solo stake ("staking requires 24/7 wallet")
This version starts by clarifying there are 2 methods to stake, and gives the beginner the most practical info from the first sentence.
=> Rewording "How to Stake"

docs/getting-started/reading-list.md, mkdocs.yml
Closes #1042 
**Copied from [liz-bagot/testrepository](http://github.com/liz-bagot/testrepository), but with the changes detailed below:**
---
Removed the following sections
```
**_Staking_** _(Link to staking section)_
**_Ticketing_** _(Link to ticketing section)_
**_Politeia_** _(Link to Politeia section)_
```
```
**_How to Send and Receive Decred_**
BLANK
```
---
Updated internal docs.decred.org URLs to relative links which will be validated by mkdocs
---
Removed the SeekingAlpha link `An analysis of Bitcoin and Decred...` as it is behind a paywall
---
- Updated dex spec link from `https://github.com/decred/dcrdex` to `https://github.com/decred/dcrdex/blob/master/spec/README.mediawiki`
- Updated Politeia blog post link from `https://blog.decred.org/2017/10/25/Politeia/` to …
=> Add Reading List.

docs/faq/wallets-and-seeds.md
Part of #1041 
I removed this question
```
How do I import a key that is in wallet import format (WIF)?
```
It was only a recurrent issue during the airdrop and is not so relevant today
=> Remove forum links from wallet/seed FAQ

docs/mining/overview.md
=> Update PoW intro. Mention fees.

docs/getting-started/reading-list.md
Implementing suggestions from #1043
=> s-ben suggestions on reading list.

conf/nginx.conf, docs/getting-started/articles-and-media.md, mkdocs.yml
=> Rename Reading List.

docs/faq/configuration.md
=> Add daemon FAQ.

.gitignore, README.md, requirements.txt
Also bumping other deps.
We can't take advantage of new mkdocs features until we update the theme we use. A new version of the theme is scheduled and should be out shortly.
=> Update to mkdocs 1.1.0

docs/getting-started/articles-and-media.md
=> Add buck54321 paper

conf/nginx.conf, docs/advanced/issuance.md, docs/glossary.md, docs/mining/overview.md, mkdocs.yml
Open to debate if anybody disagrees with the new name "Issuance"
Closes #1074
=> Rename Inflation page

docs/contributing/overview.md, docs/getting-started/obtaining-dcr.md
Preperation for decred/dcrweb#842
=> Remove links to decred.org/recruiting

docs/contributing/overview.md
=> Add contractor personal stories

docs/faq/blocks.md, docs/faq/configuration.md, docs/glossary.md
I have reviewed the forum posts that are being linked to, and confirmed that the links do not provide any additional info beyond what is already included in the docs.
#1041
=> Remove some forum links.

docs/getting-started/articles-and-media.md
Switched "Decred: Where it all began" link for one that's still live.
=> Replaced dead link

docs/contributing/contributor-compensation.md, requirements.txt
=> Info about contractor pay rates

docs/getting-started/beginner-guide.md, docs/wallets/hardware-wallets.md, docs/wallets/mobile-wallets.md, mkdocs.yml
=> Update wallets and add mobile.

conf/nginx.conf, docs/faq/proof-of-stake/solo-voting.md, docs/glossary.md, docs/research/ticket-selection-algorithm.md, mkdocs.yml
Should be merged after decred/dcrdevdocs#88
=> Remove ticket lottery page, add links to dcrdevdocs

docs/governance/politeia/example-proposals.md
Addressing the issues raised in #905. Requesting review from @RichardRed0x and @xaur who have both previously demonstrated an interest in proposal guidelines and expectations.
As this is a example proposal it should really meet all of [the guidelines](https://docs.decred.org/governance/politeia/proposal-guidelines/) so I would appreciate some help/suggestions making sure this example is up to scratch.
If you hadn't guessed, I am using [this](https://proposals.decred.org/proposals/20e967dad9e7398901decf3cfe0acf4e0853f6558a62607265c63fe791b8b124) and [this](https://proposals.decred.org/proposals/ad0f968) as inspiration
Closes #905
=> Replace example dev proposal with a larger scale one

docs/governance/politeia/proposal-guidelines.md
Also change "amounts should be specified in USD" to "amounts **must** be specified in USD".
Closes #848
=> Link to further info on proposal guidelines.

mkdocs.yml, requirements.txt
Major version bump giving us some enhanced search functionality.
https://squidfunk.github.io/mkdocs-material/changelog/#material-for-mkdocs
=> Update to mkdocs material version 6.

docs/governance/politeia/proposal-guidelines.md
=> Suggest education campaign for complex proposals

docs/css/style.css, requirements.txt
Picks up some minor bug fixes and allows the removal of some custom css.
=> Update mkdocs theme.

docs/privacy/cspp/how-to-cspp.md
=> Fix minor typo in CoinShuffle++ documentation

Dockerfile, requirements.txt
This doesnt give us any new user features but it does reduce our build size/time considerably.
Also fix a build warning by updating pip before using it.
=> Update to mkdocs 7.

docs/wallets/decrediton/migrations.md, mkdocs.yml
Adding some info due to migration introduced by https://github.com/decred/decrediton/pull/2664
=> Add decrediton/migrations page

docs/faq/configuration.md, docs/privacy/general-privacy.md
Update link to dcrd repo for service files, and update dcrdata onion link from v2 to v3.
Part of #1176
=> Fix broken links.

.gitignore, Dockerfile, docs/index.md, mkdocs.yml, requirements.txt
One of the new features is auto-generated social cards. I have set these to be disabled by default but enabled in the docker container.
I have reworked some of the page titles so they make sense when displayed on their own. For example:
-  "Home" becomes "Introduction to Decred"
- "Overview" becomes "Governance Overview"
=> Update to mkdocs-material 8.5.6.

README.md, docs/faq/configuration.md, docs/glossary.md
=> Fix: typos

.github/workflows/python.yml, Dockerfile, LICENSE, docs/about/license.md, docs/css/style.css, docs/getting-started/project-history.md, docs/governance/politeia/example-proposals.md, docs/wallets/decrediton/decrediton-setup.md, docs/wallets/decrediton/upgrading-decrediton.md, mkdocs.yml, requirements.txt
Bumping major version of mkdocs to 9. It includes some nice improvements to search but nothing else relevant to our docs.
Also picking up python 3.11 and nginx 1.22.
=> Use mkdocs-material 9.

.dockerignore, Dockerfile, bin/build.sh, bin/build_docs.sh, conf/nginx.conf
- Use Alpine version of nginx image (23MB instead of 142MB)
- Fix MIME type for rss feeds.
- Clean up .gitignore and .dockerignore.
- Ensure scripts fail on error.
=> build: Docker cleanup/update.

docs/advanced/atomic-swap.md, docs/lightning-network/watchtowers.md, docs/wallets/cli/dcrctl-rpc-commands.md, docs/wallets/cli/dcrd-and-dcrwallet-cli-arguments.md, docs/wallets/cli/startup-basics.md, docs/wallets/decrediton/decrediton-troubleshooting.md
A collection of minor nits I noticed while working on other things.
=> Minor tidying and linting.

docs/css/style.css, docs/getting-started/project-history.md
Add a few notable events which have occurred since the last update. Also minor change to make text look better when changing from light/dark mode.
=> Update project history timeline.

docs/governance/consensus-rule-voting/consensus-vote-archive.md
Adds blake3pow and changesubsidysplitr2 agendas.
=> Add vote version 10 to consensus vote archive.

docs/getting-started/business-brief.md, docs/governance/decred-constitution.md, docs/proof-of-stake/overview.md
=> Update DCP-10/12 subsidy numbers
