decred/dcrdocs

docs/mining/overview.md, docs/mining/proof-of-stake.md, docs/mining/proof-of-work.md, mkdocs.yml
I re-wrote both sections to fit into a single page.  I cut out tons of repetitive information that is mostly addressed elsewhere and targeted the content more towards a regular user doing the most common thing.
PoS - Tried to reflect the reality of things as they are today (ticket buying is a fee market now, auto buying isn't recommended and will be replaced soon, and stake pools will launch soon)
PoW - Having a ton of duplicated pages for every mining software/OS didn't make sense to me.  Solo mining is pretty much dead now so I focused on pool mining.
I unlinked the original content but left it intact in to make it easier to review and so we can crib content from those pages more easily in case we want to restore some of it.
Also needs a thorough proof-reading since I've re-written both …
=> revamp PoS/PoW material

docs/getting-started/install-guide.md, docs/getting-started/overview.md, docs/getting-started/user-guides/linux.md, docs/getting-started/user-guides/osx.md, docs/mining/proof-of-stake.md, docs/mining/proof-of-work.md, docs/mining/proof-of-work/pool-mining/gominer/windows.md, mkdocs.yml
* Remove decredstakepool.com from list of stakepools on PoS page
* Add dcrd, dcrwallet clause about separation of node/wallet software to User Guide Overview page
* Edit step 1 of the OSX and Linux user guides for clarity, link back to installation guide
* Add install-guide.md
* Add install guide to navigation
* Remove extra whitespace from PoW page and gominer Windows Guide, replace with <br />
fixes #55
=> Add Installation guide, edit existing documentation

docs/getting-started/install-guide.md, docs/getting-started/user-guides/paymetheus.md
Resolves #66 
Update to version 0.8.0. Mostly just a version bump. Can Linux/Mac users confirm their instructions are still valid?
=> Update installation guide.

docs/mining/proof-of-stake.md
* Change all links to dcrstats.com to be specified as third-party.
* Add link to stats.decred.org wherever dcrstats.com was used.
=> Add stats.decred.org as official stats page

docs/getting-started/install-guide.md
No longer part of the package as per decred/decred-release#90
=> Removing refs to `dcrticketbuyer`

docs/advanced/transaction-details.md, mkdocs.yml
Info comes from here: https://wiki.decred.org/Transaction
I have removed the section "1.1 Version, Locktime, and Expiry" because the information was mostly duplicated in the table above. I have updated the table slightly to compensate. The rest of the text remains unaltered.
Fixes #116
=> Move Transaction Details from the wiki.

docs/advanced/overview.md
The Overview page did not get updated when "Transaction Details" was added in #117.
=> Include 'Transaction Details' section in overview page

de_docs/getting-started/user-guides/dcrwallet-tickets.md, de_docs/mining/proof-of-stake.md, de_mkdocs.yml, docs/getting-started/user-guides/dcrctl-basics.md, docs/getting-started/user-guides/dcrwallet-tickets.md, docs/mining/proof-of-stake.md, es_docs/getting-started/user-guides/dcrwallet-tickets.md, es_docs/mining/proof-of-stake.md, es_mkdocs.yml, mkdocs.yml
This included an overhaul to the proof-of-stake.md to provide more higher level information about the staking protocol. This page now will link to specific guides for ticket purchase with each appliaction.
Closes #155
=> Add dcrwallet ticket purchase guide

de_docs/mining/proof-of-stake.md, docs/mining/proof-of-stake.md, es_docs/mining/proof-of-stake.md
I originally wrote the transaction sizes in kB. This PR corrects that.
=> Fix transaction sizes

docs/advanced/block-header-specifications.md
- Use field names consistently
- Make the example headers look nicer
- New line before page break so it renders properly
Closes #209
=> Minor improvements to block header page.

de_docs/getting-started/using-testnet.md, de_mkdocs.yml, docs/getting-started/beginner-guide.md, docs/getting-started/using-testnet.md, es_docs/getting-started/using-testnet.md, es_mkdocs.yml, mkdocs.yml
This PR adds the Using Testnet Guide (/getting-started/using-testnet.md), and recommends using the testnet to beginners on the beginner-guide.md page.
Because testnet2 currently requires compiling from source, I think this PR should be held until new binaries are released, but comments, criticisms, etc,.. much appreciated.  
Closes #78
=> Add using-testnet.md

de_mkdocs.yml, docs/getting-started/user-guides/decrediton-setup.md, es_mkdocs.yml, mkdocs.yml
Alpha label and warning were removed from decrediton software
so it should be removed from docs.
Closees #319
=> Remove alpha label from decrediton info.

docs/advanced/manual-cli-install.md
Changed **Mac** and **OS X** to **macOS**, since Apple's operating system name has changed. [https://www.apple.com/macos/sierra/](https://www.apple.com/macos/sierra/)
=> macOS Inconsistency

docs/getting-started/cli-differences.md
Changed **macOS/OSX** to **macOS**, since Apple's operating system name has changed. [https://www.apple.com/macos/sierra/](https://www.apple.com/macos/sierra/)
=> macOS Inconsistency #1

docs/getting-started/startup-basics.md
Changed **macOS/OSX** to **macOS**, since Apple's operating system name has changed. [https://www.apple.com/macos/sierra/](https://www.apple.com/macos/sierra/)
=> macOS Inconsistency #2

docs/getting-started/user-guides/cli-installation.md
Changed **OSX/macOS** and **Mac** to **macOS**, since Apple's operating system name has changed. [https://www.apple.com/macos/sierra/](https://www.apple.com/macos/sierra/)
=> macOS Inconsistency #3

docs/getting-started/user-guides/decrediton-setup.md
Changed **Mac** and **macOS/OSX**  to **macOS**, since Apple's operating system name has changed. [https://www.apple.com/macos/sierra/](https://www.apple.com/macos/sierra/)
=> macOS Inconsistency #4

docs/advanced/verifying-binaries.md, docs/getting-started/user-guides/dcrctl-basics.md, docs/getting-started/user-guides/dcrd-setup.md, docs/getting-started/user-guides/dcrwallet-setup.md, docs/getting-started/user-guides/dcrwallet-tickets.md, docs/getting-started/using-testnet.md
Changed **macOS/OSX**  to **macOS**, since Apple's operating system name has changed. [https://www.apple.com/macos/sierra/](https://www.apple.com/macos/sierra/)
=> macOS Inconsistency #5

docs/mining/proof-of-stake.md
This doc currently says skatevoters can
> vote a block invalid if it doesn't match to the consensus rules
But that's technically incorrect. If a block doesn't match the consensus rules, it can't be mined on top of (no stakeholder action needed). The power of stakeholding is being able to reject otherwise **valid** blocks for whatever reason.
=> Fix incorrect staking information

docs/mining/proof-of-work.md
right now the link to decredpool.org is broken as in ([decredpool.org](http://decredpool.org)) and should be like this: ([www.decredpool.org](http://www.decredpool.org))
=> proof-of-work: add www before decredpool to prevent broken link

docs/advanced/contributing.md, docs/advanced/contributor-compensation.md, docs/advanced/user-projects.md, docs/advanced/using-github.md, mkdocs.yml
- Move `User Projects` and `Contribution Guidelines` into a new `Contributing` section
- Rename `User Projects` to `Contributor Projects`
- Split `Contribution Guidelines` into `Using GitHub` and `Source Code Contributions` - some contributors are new to GitHub and don't necessarily need the extra overhead of golang/javascript specifics.
- New `Contributor Compensation` page which describes the old RFP process and the new contractor process. Links into the blog post for full details.
=> Introduce `Contributing` section.

docs/advanced/block-header-specifications.md
This modifies the block header specification so that the comments on the example encoded block header line up with each other to ease readability and also corrects the `PoolSize` reference.  Also, it updates the example encoded block header as raw bytes to use the available space so it more closely matches the example `getwork` response below it.
=> Update block header examples.

docs/mining/how-to-stake.md
- bump to latest 1.1.3 version
- whitespace/capitalization cleanup
- link directly to https://decred.org/stakepools/ now that we have a proper link to it
- remove mention to Paymetheus since it's now deprecated
=> Update how to stake instructions

theme_override/base.html, theme_override/partials/social.html
- Absolute path for Font Awesome style
- Include base url in path for Material Icons style
This should help with pages such as:
https://docs.decred.org/getting-started/using-the-block-explorer/
which currently 404 on the Font Awesome and Material CSS in the live documentation site.
=> Update theme override paths for fonts & icons

docs/governance/governance.md, docs/governance/politeia.md
This is to bring the description of Politeia on the governance and politeia pages in line with some corrections to the onboarding copy (see [this PR](https://github.com/decred/politeiagui/pull/584))
=> minor fix to governance/politeia pages

docs/governance/politeia.md
Adds politeiavoter CLI tool as option for voting ( Closes #664 ). This tool is stable and in use. The README documentation on the linked repo is solid (confirmed by ay-p on Slack).
=> Adds politeiavoter CLI option to Pi page

docs/governance/politeia.md
Adds current quorum and approval thresholds (20%, 60%) to 'Submitting and approving proposals' section of Pi page.
(Closes #666 ). 
.-._                                                   _,-,
`._`-._                                           _,-'_,'
`._ `-._                                   _,-' _,'
`._  `-._        __.-----.__        _,-'  _,'
`._   `#==="""           """===#'   _,'
`._/)  ._               _.  (\_,'
)*'     **.__     __.**     '*(
=> Updates requirements for quorumm and approval thresholds

docs/mining/proof-of-work.md
Removes out-of-date numbers on block reward. Removes advice to mine on video card, adding note that ASICs are out now, making GPU mining unlikely to be profitable. ( Closes #674 ).
=> Updates PoW page with up-to-date info on block rewards, GPU mining

docs/wallets/web.md
Removes a link, `(See: FAQ)`, which was just linking to the page it was on (inception link) ( Closes #688 ). Couldn't find a relevant page to link to - neither of the two FAQs that deal with wallets actually reference what the link points to. Also, some want to remove the web wallet documentation entirely (opening separate Issue for that).
=> Removes bad link web wallet

docs/governance/consensus-rules-voting.md, docs/governance/introduction-to-decred-governance.md, docs/governance/politeia.md, mkdocs.yml
Capitalizes all significant words in titles for two pages in the governance section, making these pages consistent with the rest of the pages in dcrdocs ( Closes #714 ).
=> Fixes capitalization governance pages

docs/advanced/navigating-politeia-data.md
Cleanup and formatting specified in original PR ( Closes #698 ). 
In addition to basic cleanup (replacing bulleted lists w/ tables, removing double spaces), did some rewording for flow, and added two new subheadings for organization.
=> Cleans up formatting, tweaks wording

docs/glossary.md
We just updated the standard transaction fee from 0.001 DCR/kB to 0.0001 DCR/kB. This PR updates this number in the glossary ( Closes #742 ).
=> Updates standard transaction fee in glossary

docs/faq/proof-of-stake/stake-pools.md, docs/governance/how-to-vote.md, docs/mining/how-to-stake.md, docs/research/decentralized-stake-pooling.md
Replaces all instances of `Pool.svg` icon with `Servers.svg` icon, to reflect jargon change ( "Stakepool" -> "Voting Service Provider") ( Closes #740 ).
=> Updates outdated stakepool logo

docs/advanced/transaction-details.md
This PR removes two unnecessary serialization formats and improves the definition of the `Version` parameter in the Transaction Format table ( Closes #760 ). 
Note: we also want to include an example transaction, but I ran out of time (headed traveling tomorrow). Have broken off the example transaction (including example tx provided by @davecgh) into a separate Issue: https://github.com/decred/dcrdocs/issues/765
=> Updates transaction details page

docs/getting-started/beginner-guide.md, docs/governance/politeia.md, docs/governance/politeia/example-proposals.md, docs/governance/politeia/politeia.md, docs/governance/politeia/proposal-guidelines.md, docs/index.md, docs/mining/proof-of-stake.md, httpd.conf, mkdocs.yml
Now that we've had Pi running for a while (and have updated copy in the Pi modal), it's time to updated and flesh out the Pi documentation on dcrdocs. This PR:
- Updates the proposal steps wording to match updated copy in Pi modal ( Closes #753 )
- Creates new page for example proposals ( Closes #752 )
- Creates new /Politeia submenu to house Pi docs (we have 3 pages now) ( Closes #754 )
- Creates new proposal guidance page, repurposing [Pi rant about bad proposals](https://proposals.decred.org/proposals/85fc65cef080cfc3564906fd3d488b827d74fc99bb29143ed8aa6c400b765be9/comments/2)
- General editing for flow
=> Updates Politeia docs 

docs/advanced/navigating-politeia-data.md
The [Navigating Politeia Data](https://docs.decred.org/advanced/navigating-politeia-data/) page is missing definitions for the `signature` and `receipt` parameters in the `comments.journal` file. This PR adds those definitions ( Closes #697 ).
=> Adds definition signature, receipt for comments.journal file

docs/faq/proof-of-stake/voting-tickets.md
This PR is meant to address #382. Clarification is added to specify that missed tickets are not automatically revoked when staked via Decrediton and adds instruction on how to revoke.
=> Added note to click revoke ticket for missed tickets when using GUI

docs/about/license.md, mkdocs.yml
Two benefits of removing this:
- Site works better when running in different locations (eg. locally) - All links default to the current instance (`/`) rather than some of them pointing incorrectly to docs.decred.org
- Fixes the 404 page (ref. https://github.com/mkdocs/mkdocs/issues/1598) (Closes #787)
One drawback:
-The only significant feature depending on this config is canonical links in the HTML headers. I consider this an acceptable loss - we don't need canonical links because we only host the docs in one place.
=> Remove site_url config.

docs/contributing/source-code-contributions.md, docs/contributing/using-github.md, docs/getting-started/beginner-guide.md
Also removes Rocket chat, as we removed it from https://decred.org/community
Closes #447
=> Link to community page instead of listing irc/slack.

docs/advanced/address-details.md, docs/faq/wallets-and-seeds.md, docs/glossary.md, mkdocs.yml
This PR creates a 'Address details' page under /Advanced ( Closes #779 , Closes #710 ). Previously, technical details about addresses were found in the glossary definition for Address and a couple FAQ questions. An advanced page seemed like a better place to aggregate this information. Have also added the table @zubairzia0 added in Issue https://github.com/decred/dcrdocs/issues/710 (@jholdstock maybe this finally closes that issue?). The glossary definition of address and relevant FAQ questions have also been updated to be more concise and point to the new address page.
=> Adds address details page

docs/faq/proof-of-stake/general.md, docs/getting-started/beginner-guide.md, docs/glossary.md, docs/governance/consensus-rule-voting/consensus-rules-voting.md, docs/governance/consensus-rule-voting/consensus-vote-archive.md, docs/governance/how-to-vote.md, docs/governance/introduction-to-decred-governance.md, docs/index.md, docs/proof-of-stake/proof-of-stake.md, httpd.conf, mkdocs.yml
The single page for Consensus Rule Voting is getting rather long, and with another vote around the corner, it's about to get longer.
This PR moves the voting archive into its own page. No new copy or content is introduced here, just moving and refactoring things.
- Embed images using markdown syntax instead of html
- Use headers correctly in the archive
=> Move voting archive into its own page.

docs/advanced/manual-cli-install.md, docs/wallets/cli/cli-installation.md, docs/wallets/decrediton/decrediton-setup.md, mkdocs.yml, requirements.txt
Closes #584 
Introduces a new mkdocs plugin to parse md markup and add template variable functionality
https://github.com/rosscdh/mkdocs-markdownextradata-plugin
Edit the `mkdocs.yml` and add `extra:` variables:
```yaml
extra:
decreditonversion:
windows: 1.3.1
linux: 1.3.1
mac: 1.3.1
cliversion:
windows: 1.3.0
linux: 1.3.0
mac: 1.3.0
```
`extra:` variables were only available in the html themes, but the plugin enables the use further down in the markup files.
In the `*.md` files use the template variables by using:
```jinja
{{ decreditonversion.windows }}
{{ cliversion.linux }}
```
=> Add version numbers as template variables

conf/nginx.conf, docs/governance/consensus-rule-voting/consensus-rules-voting.md, docs/governance/consensus-rule-voting/how-to-vote.md, mkdocs.yml
Moves the 'How to Vote under Consensus Rule Changes' page under the 'Consensus Rule Voting' menu ( Closes #839 ). Also, as it's clear from the menu now what is being voted on, have renamed 'How to Vote under Consensus Rule Changes' to 'How to Vote'.
Menu now looks like this:
=> Move How to Vote under Consensus Rule Changes

mkdocs.yml
It appears search disappeared when we added template variables in PR https://github.com/decred/dcrdocs/pull/645. This happened because previously, search was enabled by default in MkDocs. So when we added our first plugin to `mkdocs.yml`, the default was overwritten, removing search. This PR fixes this by explicitly adding it back ( Closes #845 ).
=> Restores search plugin

docs/faq/proof-of-stake/general.md, docs/faq/proof-of-stake/voting-service-providers.md
Adds a question to the PoS Voting General FAQ ( Closes #822 ).
Voting rights are based on 1-of-2 multisig transactions. Therefore, in the unlikely event your Voting Service Provider (VSP) goes down permanently, you can still vote and receive your PoS reward, as well as revoke a missing or expired ticket. To do this, you will need to have a wallet with your VSPs pool script imported. See the [Solo Proof-of-Stake (PoS) Voting](../../advanced/solo-proof-of-stake-voting.md) page for details on setting up a wallet for solo voting.
=> New question for FAQ for PoS voting

docs/faq/errors.md, docs/faq/proof-of-work-mining.md, docs/proof-of-stake/proof-of-stake.md, mkdocs.yml
Moves the PoS FAQ pages to under the top-level FAQ menu ( Closes #833 ). 
Renames the 'What is Proof-of-Stake?' page to 'Overview', as discussed [here](https://github.com/decred/dcrdocs/issues/814), making it consistent with the PoW 'Overview' page.
Also, while I was here, did some minor cleanup around naming consistency. Just changing instances of 'Proof of Stake/Work' with 'Proof-of-Stake (PoS'), Proof-of-Work (PoW), to make them consistent with other pages in the docs. 
@jholdstock , realize I'm bundling together a few small issues here. Can break into separate PRs if you think that's better.
=> Reorganizes FAQs, renames 'What is Proof-of-Stake?' page 

docs/advanced/using-testnet.md
This PR adds a list testnet VSPs to the testnet page, along with a sentence explaining why one would need a testnet VSP ( Closes #855 ).
=> Add list of testnet VSPs to testnet page

docs/advanced/manual-cli-install.md, docs/advanced/solo-proof-of-stake-voting.md, docs/wallets/cli/cli-installation.md, docs/wallets/cli/dcrctl-rpc-commands.md, docs/wallets/cli/dcrd-and-dcrwallet-cli-arguments.md, docs/wallets/decrediton/decrediton-setup.md, docs/wallets/decrediton/using-decrediton.md, mkdocs.yml
There is no precedent for release versions being different per operating system, so this PR consolidates the win/mac/linux variables into one. Also makes use of `cliversion` variable in the solo PoS guide.
=> Refine use of variables.

docs/governance/politeia/example-proposals.md, docs/governance/politeia/proposal-guidelines.md
Adds tip to the proposal guidelines page that reminds proposers to explain complex concepts and jargon in a way all stakeholders can understand ( Closes #876 ). Also updates the example software proposal to adhere to this tip.
=> Proposal guidelines: advice to mind target audience

docs/wallets/cli/dcrctl-rpc-commands.md
Adding links to technical documentation on GitHub for RPCs on dcrd and dcrwallet ( Closes #874 ).
=> Adds more detail about RPC commands

docs/wallets/cli/dcrwallet-tickets.md
- It doesnt matter which section of `dcrwallet.conf` you put settings into. Sometimes the sections dont event exist
- Remove mentions of ticketbuyer fee calculations, not applicable to v2 ticketbuyer.
- `purchaseticket` has an argument for `ticketfee` in 1.4.0
Closes #865
=> Update dcrwallet-tickets.md for release 1.4.0

docs/proof-of-stake/ticket-splitting.md
Also markdown linting (whitespace only)
=> Fix broken link on ticket splitting guide.

docs/glossary.md, docs/governance/consensus-rule-voting/consensus-rules-voting.md
Overhaul the consensus vote overview page.
- Brief introduction to what consensus rules are
- Include the DCP stage in the change process
- Make it clear that the code is written and deployed *before* voting, and activated *automatically* if vote is successful
- Link to glossary for explanations of RCI and SVI
Also, in `glossary.md`:
- Add "double-spend"
- Comma seperation for four digit numbers
- General whitespace linting
=> Overhaul consensus voting overview.

docs/governance/consensus-rule-voting/consensus-rules-voting.md, mkdocs.yml
Polishing pass on the[ overhauled ](https://github.com/decred/dcrdocs/pull/890) consensus rule voting page. Mainly just rewording for flow. Have also changed the menu title from 'Consensus Rules Voting' to 'Overview' for consistency with other menus (e.g. PoW, PoS menus).
=> Polishes text consensus rule voting page

docs/proof-of-stake/ticket-splitting.md
As [pointed out](https://matrix.to/#/!tfqymymiNgzSUJTHqS:decred.org/$155372786444640AqyRy:decred.org?via=decred.org&via=matrix.org&via=zettaport.com) in #Documentation the link to decredvoting.com was actually going to `https://stake.decredbrasil.com`. This PR changes it to the correct `https://decredvoting.com/`.
Also updating the download link to point to the main releases, not a specific version.
=> Fixes link on ticket splitting page

docs/proof-of-stake/ticket-splitting.md
Explain that voting rights are assigned differently for on-chain votes and politeia votes.
I have removed the bit about being able to game the system, because at the moment it is still possible to game politeia voting this way, and we dont want to give the reader any ideas. That detail is still mentioned in the algorithm link.
=> ticket splitting: diff between on-chain votes and pi votes.

docs/governance/politeia/example-proposals.md
This commit updates the example Politeia proposal for a software fearure, so that it complies with our recently [updated proposal guidelines](https://github.com/decred/dcrdocs/pull/896). Notably, we add which software license the proposed software would use and are clearer on the draw schedule.
=> Updates proposal example to comply with updated proposal guidelines

docs/faq/proof-of-stake/general.md, docs/proof-of-stake/proof-of-stake.md
Removing two **very** lengthy FAQs, which are just duplicating information found elsewhere and providing nothing new.
Also linting `proof-of-stake.md`, which includes removing a rogue `<br />`
=> Remove unnecessary PoS FAQs.

docs/proof-of-stake/ticket-splitting.md
=> Remove decrediton version from ticket splitting guide.

docs/advanced/inflation.md, docs/advanced/premine.md, docs/faq/general.md, mkdocs.yml
Moves the existing content out of FAQ and into its own page. Also adds a section on how the airdrop was implemented.
Also adds some extra links:
- extra blog post for origins of decred
- extra links for the premine, airdrop etc.
Relates to #615
=> Create a new page for premine.

docs/advanced/premine.md, mkdocs.yml
This commit polishes text on the new premine page, which was a bit rough. Notably, the page reused text from an old announcement, which was in present tense. Have reworded to use past tense, wordsmithed for flow, and improved formatting.
=> Polishes text premine page

docs/wallets/hardware-wallets.md, mkdocs.yml
Adding a page on hardware wallets ( Closes #840 ). 
We might want to add more detail to this, such as any DCR-specific instructions/limitations, or short product descriptions?
=> Adds hardware wallet page

docs/governance/overview.md, docs/index.md
Rewrote [Introduction to Decred Governance](https://docs.decred.org/governance/overview/) page to accomplish a few goals:
- Adds more detail on block voting ( Closes #912 )
- Restructures text to better reflect role of Politeia in governance
- Improves flow
- Removes intro text at top (which is basically a duplicate of intro text on the [home page](https://docs.decred.org/)). Have also moved text showing pronunciation of Decred to the home page (where I think it belongs).
=> Overhauls intro to governance page

docs/css/style.css
Fix an issue where the top nav menu and collapsed side nav menu were showing the github panel in different colors:
=> fix side nav menu header color.

docs/advanced/general-security.md, mkdocs.yml
Have created a first draft of a general security page ( Closes #799 ). Have added this as a page in the Advanced section. Basically this is just cleaning up and re-organizing a post written by @behindtext, with the content separated into `System setup` and `Operations security (OPSEC)`, with the listed security measures in (rough) order of ascending severity.
=> Adds general security page

docs/advanced/transaction-details.md
Adds an example transaction to the [Transaction Details](https://docs.decred.org/advanced/transaction-details/) page ( Closes #765 ). 
Note: the transaction fields were broken down according to the example tx provided in #765 by @davecgh, and when parsing the data I ended up moving a couple bytes around. E.g. `script version` in the example was `0000`, but the docs say this is a two byte field, so have used `00` and moved the subsequent `00` into the next field (`script length`). There are also a couple fields that need double checking, such as `public key signature length` (hex evaluating to 25, though looks like the script has 50 bytes?) and `signature script length`. 
Also, the markdown table is a bit wonky, due to the fact that markdown doesn't support spanning cells. Can tweak the …
=> Adds transaction example 

docs/advanced/block-header-specifications.md
In the [Block Header Specifications](https://docs.decred.org/advanced/block-header-specifications/) page, have updated definition of the VoteBit parameter to reflect that VoteBits are now also used for voting on consensus rule changes.
=> Update definition VoteBits in block header page

docs/index.md
On the docs homepage, we reference PoW without spelling it out. A nitpick for sure, but it's the homepage, we should spell out Proof-of-Work (PoW) properly.
=> Spell out PoW on homepage

docs/wallets/lightning.md, mkdocs.yml
This PR creates a simple 'Lightning Network (LN)' page under wallets. There's a lot of info I can think to add here (Decredition support, how to set up and operate nodes, etc.), but I realized we probably don't want to add that to dcrdocs until there's an official release of Decrediton that supports LN. We could start adding more technical details in a new page under '/Advanced', but a page under '/Wallets' should be more end user oriented. 
I'm tempted to say let's hold off on this page until there's something a user can use without having to compile from source, but it's also awkward that we're promoting our Lightning launch and don't have it in the docs at all. Thoughts?
=> 1st draft LN page

docs/advanced/inflation.md
Per this [discussion](https://matrix.to/#/!MgQoetFiyjrHAywokv:decred.org/$15668471348365WoNgw:decred.org?via=decred.org&via=matrix.org&via=zettaport.com), we want to explain the ~21M hard cap.
This PR adds a short explanation of the hard cap design decision to the Inflation page ( Closes #975 ).
=> Add explanation hard cap inflation page

mkdocs.yml
Decred's Medium page is an important source of information when it comes to Decred knowledge. It should be referenced from Decred documentation.
=> Add Decred Medium page to social links

docs/css/fonts.css
Social links at the bottom of every page are made pretty with font-awesome icons. They are currently bolded, which makes them look weird.
=> Remove font-weight:bold from fa icons

docs/advanced/atomic-swap.md, mkdocs.yml
=> Add atomic swap to docs

docs/governance/politeia/example-proposals.md, docs/governance/politeia/proposal-guidelines.md
Updates the proposal guidelines and example proposal pages to specify that payment amounts must be in USD ( Closes #982 ).
=> Specify proposal amounts in USD

docs/advanced/full-node.md, mkdocs.yml
Adds a page with instructions for setting up a Decred full node ( Closes #987 ). 
Have used @noahpierau's [draft](https://github.com/noahpierau/articles/blob/master/how-to-run-a-decred-full-node.md) as a baseline, adding in material from some other guides I found in doing my research:
- _Checkmatey's guide (@checkmatey): https://medium.com/@_Checkmatey_/running-a-decred-raspberry-pi-node-ac605b70c652 
- Stakey.club (anyone know their GitHub?):: https://stakey.club/en/installing-dcrd/
- Pablito's guide (anyone know his GitHub?): https://medium.com/crypto-rocket-blog/my-experience-setting-up-a-decred-full-node-8a9bbf55bc30
I know the external IP address will no longer be needed in v1.5.0, but don't want to include anything about that until the release.
=> Adds full node setup page

docs/getting-started/beginner-guide.md
**NOTE: do not merge until developer documentation is launched.**
Adds links to devdocs. The beginner guide was the only obvious place I could see. Open to ideas for other links.
Also sneaking in small edit on the beginner guide: updating a link to point to the Contributing section instead of the recruitment blog (Contributing section already links to recruitment blog).
=> Add links devdocs

docs/advanced/premine.md
Per @degeri's [comment](https://matrix.to/#/!tfqymymiNgzSUJTHqS:decred.org/$157632331763516GZMwK:decred.org?via=decred.org&via=matrix.org&via=zettaport.com) in #Documentation, scammers sometimes promote fake airdrops to steal DCR. This PR adds a warning to the premine page warning users about this.
=> Adds warning scam airdrops

docs/img/collision_resistance.svg, docs/img/haifa.svg, docs/img/length-extension.svg, docs/img/merkle-damgard_construction.svg, docs/img/preimage_resistance.svg, docs/img/second-preimage_resistance.svg, docs/img/wide-pipe.svg, docs/research/blake-256-hash-function.md
BLAKE-256 page updates. The update is based on various academic sources as well as on NIST reports. I have created some illustrations in SVG to explain some concepts, as well. 
closes #947
=> Updating BLAKE-256 page

docs/glossary.md
Goes some way to explaining #922, but doesnt close the issue because it does not explain what the warning means or its implications.
=> Add Coin Type and HD Wallet to glossary.

docs/advanced/mnemonic-seed.md, mkdocs.yml
A new page that explains the user-facing differences between Decred and BIP39 seeds. 
closes #1066
=> Decred & BIP39 Seed

docs/advanced/full-node.md, docs/advanced/manual-cli-install.md, docs/wallets/cli/cli-installation.md, docs/wallets/decrediton/decrediton-setup.md, docs/wallets/decrediton/upgrading-decrediton.md
Since new users may be unfamiliar with the concept of verifying binaries, the following pages were updated to encourage users to follow good security practices:
advanced/full-node.md
advanced/manual-cli-install.md
wallets/cli/cli-installation.md
wallets/decrediton/decrediton-setup.md
wallets/decrediton/upgrading-decrediton.md
First-time Decrediton users will potentially be the most novice, and were only ever directed to Decred.org/downloads, so I tried to emphasize that verifying binaries is an *optional* security step by listing it inside step 1 in its own admonition block. I also added links to the manifest there.
=> multi: encourage users to verify binaries

docs/faq/proof-of-stake/voting-service-providers.md, docs/proof-of-stake/how-to-stake.md, docs/proof-of-stake/redeem-script.md, docs/wallets/decrediton/using-decrediton.md, mkdocs.yml
First draft to solve #1065
- Added new Redeem Script page under Proof-of-Stake
- Updated Using Decrediton "Backup redeem script" warning to state the risks
- Added a similar warning to the PoS/How to Stake page
- Added "9. My VSP went down and I lost the redeem script, is there a way to recover it?" to the FAQ under PoS/VSP.
Added the new page under Proof-of-Stake, it is a much more visible place than the FAQ, but it could be moved to the FAQ if we want to keep the Proof-of-Stake section clean of specific solo/vsp info.
=> Add Redeem Script page

docs/advanced/manual-cli-install.md
Windows releases are not packages in tar files anymore.
=> Remove note about .tar.gz on Windows

docs/lightning-network/backups.md, mkdocs.yml
Ideally the page should show Decrediton screenshots but the relevant PR is still open (https://github.com/decred/decrediton/pull/2535) and the UI design isn't final yet so after this is merged I'll open an issue to track and add the screenshots that reflect an actual released version.
=> Add page about LN backups

docs/mining/overview.md, docs/privacy/general-privacy.md
Fix the path to 'Luxor' mining pool
* https://mining.luxor.tech/decred > https://mining.luxor.tech/coins/decred
Fix the path to 'Github'
* https://github.org/decred/dcrdata > https://github.com/decred/dcrdata
=> FIXED 2 broken paths

.github/workflows/python.yml, docs/css/fonts.css, requirements.txt
Discovered in #1103, generic font-family names should not have quotes: https://developer.mozilla.org/en-US/docs/Web/CSS/font-family
Also taken the opportunity to update build deps.
Closes #1103
=> Remove quotes from generic font-family names

docs/wallets/decrediton/decrediton-troubleshooting.md
The path to Decrediton config is wrong, it is with lowercase `decrediton`.
=> Wallets -> Decrediton -> Troubleshooting - fix macos config path

docs/advanced/solo-proof-of-stake-voting.md, docs/proof-of-stake/how-to-stake.md, docs/wallets/cli/dcrwallet-setup.md, docs/wallets/decrediton/decrediton-setup.md, docs/wallets/decrediton/using-decrediton.md, mkdocs.yml, requirements.txt, snippets/script-warning.md, snippets/seed-warning.md
Using the snippets plugin allows the removal of markdown formatted content from a .yml config file. This was always an abuse of the config file, and using the plugin is a more proper solution.
=> Use snippets plugin.

docs/advanced/manual-cli-install.md, docs/css/style.css, docs/wallets/cli/cli-installation.md, docs/wallets/decrediton/decrediton-setup.md, mkdocs.yml
This PR makes use of proper tabs for OS specific installation instructions rather than collapsable panels.
Also:
- Remove list of files which should be included in the release tar. Its unnecessary and prone to falling out of date (it already is).
- Remove overly specific edge case for installing on macOS Sierra
- Move a warning in decrediton-setup.md so it appears only once in source code, rather than three times.
=> Use tabs for OS specific instructions.

docs/contributing/overview.md
Linking to the devdocs projects page instead of github.com/decred ensures we also include projects which are not under the decred GitHub org.
Closes #1145
=> Link to devdocs for software projects.

docs/wallets/cli/dcrwallet-tickets.md
I have written changes to the dcrwallet-tickets.md page to add steps for staking with a VPS via vpsd as of v1.6.0, as well as added verbiage to differentiate steps that refer to the legacy method of purchasing tickets and delegating voting rights to a VSP.
=> Updates dcrwallet-tickets.md with steps for v1.6

docs/css/fonts.css, docs/css/style.css, mkdocs.yml, requirements.txt
Upgrades mkdocs-material to 7.1.0 which picks up the new palette toggle feature.
All existing custom colours are extracted into a custom made theme "dcrdocs-light", and a new "dcrdocs-dark" theme is added.
Some of the custom Decred icons don't look so great because their colors are hard-coded - will fix this up later.
Thanks for @squidfunk for this long awaited feature!
=> Dark mode.

docs/advanced/operating-a-vsp.md, docs/faq/proof-of-stake/general.md, docs/faq/proof-of-stake/voting-service-providers.md, docs/privacy/cspp/overview.md, docs/proof-of-stake/overview.md, docs/wallets/cli/dcrwallet-tickets.md
- Update `operating-a-vsp.md` to be more vspd specific. Remove monitoring demonstration. Mention staying in touch with community for updates. (Closes #1169)
- Remove mentions of multisig tickets.
- Remove dcrstats link.
- Remove cspp limitations which have now been overcome.
Closes #1157
Closes #1138
=> Various vspd updates.

README.md
Wanted to directly link to the Material for Mkdocs documentation, because I had forgotten how to use their annotations and admonitions.
=> Readme: link to mkdocs documentation.

LICENSE, docs/about/license.md, docs/advanced/manual-cli-install.md, docs/advanced/verifying-binaries.md, docs/wallets/cli/cli-installation.md, docs/wallets/cli/dcrctl-rpc-commands.md, docs/wallets/cli/dcrd-and-dcrwallet-cli-arguments.md, mkdocs.yml
Files reviewed so far:
* advanced/manual-cli-install.md
* Added file for Apple M1 chip
* Added BSD. Could be useful for SEO in addition to suggesting a highly secure OS
* wallets/cli/dcrd-and-dcrwallet-cli-arguments.md
* Split apart the arguments tables into more-easy-to-read categories, just following what was done in the `config.go` sections of both dcrd and dcrwallet.
* Added some missing commands, which exist in dcrd
* Fixed minor typos or added minor clarifying text.
=> Bump for cli 1.7.2

docs/getting-started/using-the-block-explorer.md
Based on [this reddit thread](https://www.reddit.com/r/decred/comments/uqrdpa/comment/i8su4lb/) from Dave, and noticing that it caused confusion while PhoenixGreen was making an informational video, I decided to update the docs to be more accurate.
The first commit is just to correct the problems that Dave mentioned.
The second commit is to tidy things up a bit, and to reorganize the structure so that it more closely matches the [dcrdata api](https://dcrdata.decred.org/api/block/661673/verbose?indent=true). This organization is a bit subjective, but I felt like the previous structure didn't have any rhyme or reason, so why not just try to follow dcrdata.
=> Using the Block Explorer: Update & Reorganize

docs/contributing/overview.md
This is a minor cleanup and didn't think it'd be worth creating an issue for.  [Remove contractors page](https://github.com/decred/dcrweb/pull/1047) by @jholdstock has been merged on dcrweb. So it seems right to not reference that page as it will be a 404 error.
=> remove mention of contractors portrait page

mkdocs.yml
By default `mkdocs serve` will only watch the `docs/` directory for changes. Adding the snippets dir means that live-reload will work when snippets are changed.
=> Add /snippets to watched directories

docs/mining/overview.md, docs/proof-of-stake/how-to-stake.md, docs/wallets/cli/dcrd-setup.md
The icons don't work at the moment. Removing them completely makes more sense than fixing them because we are only using them in a small number of places which makes them look out of place.
=> Remove fa-icons.

docs/css/style.css
Our custom theme was missing color variables for code syntax highlighting which resulted in some hard to read text, particularly in dark mode.
=> Add synxtax highlighting to custom theme.

mkdocs.yml
Source Sans Pro is now named Source Sans 3. Using the old name in `mkdocs.yml` was causing the build to fail..
https://github.com/adobe-fonts/source-sans/issues/192
=> Update font name to "Source Sans 3"

.github/workflows/docker.yml, .github/workflows/python.yml, LICENSE, docs/about/license.md, mkdocs.yml, requirements.txt
Includes lots of minor bug fixes, a smaller docker image, faster build times, and using a new emoji extension.
=> Update mkdocs-material to 9.5.21.

docs/faq/general.md, docs/getting-started/articles-and-media.md, docs/getting-started/beginner-guide.md
Solves #1237 and updates other broken links
=> Fix thedecreddigest links (.org > .com)

Dockerfile
This will automatically accept any questions asked by apt and prevent the build from failing.
=> docker: Add -y to apt install.

docs/advanced/solo-proof-of-stake-voting.md, docs/faq/proof-of-stake/general.md, docs/getting-started/articles-and-media.md, docs/getting-started/beginner-guide.md, docs/glossary.md, docs/governance/overview.md, docs/index.md, docs/research/schnorr-signatures.md, docs/wallets/cli/dcrwallet-tickets.md, docs/wallets/cli/startup-basics.md, docs/wallets/decrediton/decrediton-troubleshooting.md, docs/wallets/spv.md
=> Fix/Remove Broken links
